spring.application.name=spring-ai-multi-provider-client
spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}
spring.ai.zhipuai.base-url=https://open.bigmodel.cn/api/paas/
spring.ai.zhipuai.api-key=${ZHIPU_API_KEY}
spring.ai.chat.client.enabled=false
